### ISSUE TITLE
Why use L_S___S_S_S__S_L for the names on line 371 in minecraft.cpp?

### ISSUE THREAD

**Issue by ElectronicallyE** [nikisalli/esp32-minecraft-server#2]
In 'minecraft.cpp', line 371 contains the following JSON:

```
{
  "version": {
    "name": "1.16.5",
    "protocol": 754
  },
  "players": {
    "max": 5,
    "online": 5,
    "sample": [
      {
        "name": "L_S___S_S_S__S_L",
        "id": "00000000-0000-0000-0000-000000000000"
      },
      {
        "name": "L_SS__S_S_S_S__L",
        "id": "00000000-0000-0000-0000-000000000001"
      },
      {
        "name": "L_S_S_S_S_SS___L",
        "id": "00000000-0000-0000-0000-000000000002"
      },
      {
        "name": "L_S__SS_S_S_S__L",
        "id": "00000000-0000-0000-0000-000000000003"
      },
      {
        "name": "L_S___S_S_S__S_L",
        "id": "00000000-0000-0000-0000-000000000004"
      }
    ]
  },
  "description": {
    "text": "esp32 server"
  }
}
```

**Questions**
- Why did you use "L_S___S_S_S__S_L" and similar as placeholder names?
- If I wanted to add additional users, would I have to add additional names and IDs?
- Why do you specify 5 users here if the MAX_PLAYERS specified in config_edit_me.h is 2?
- Why does the 'docs' directory and 'server_ping.json' (which contains the same JSON) exist? I can't see any reference to it in the code and was able to successfully compile the code with those files deleted.

**Comment by nikisalli** [comment]
docs is just some random folder I used to store captured data, I left it there cause maybe it could be of help to someone else, guess I could choose a better name lol

server_ping.json well I see you didn't see what I did there lol

L_S___S_S_S__S_L
L_SS__S_S_S_S__L
L_S_S_S_S_SS___L
L_S__SS_S_S_S__L
L_S___S_S_S__S_L

it's my name lol it is what you see when you hover over the server in the multiplayer menù, you get the ascii art

**Comment by nikisalli** [comment]
remember to close the issue if you don't have any more questions

**Comment by ElectronicallyE** [comment]
Thanks for such a quick reply @nikisalli. Would you mind explaining how you were able to create minecraft.cpp? How did you know what the was needed for the barebones server to operate? Did you start with an existing project and delete content?

**Comment by nikisalli** [comment]
I did all this from scratch, I just captured the traffic between a working server and client using wireshark and emulated the startup packages and added all the necessary packages as the client gave me errors until it became stable with no more errors

**Comment by ElectronicallyE** [comment]
Great effort mate, that's brilliant!
