### ISSUE TITLE
Attempt to Reconnect to Wi-Fi if the ESP32 Disconnects

### ISSUE THREAD

**Issue by ElectronicallyE** [nikisalli/esp32-minecraft-server#3]
Hi @nikisalli,

If the ESP32 disconnects from Wi-Fi, there is currently no code which tries to connect the ESP32 back to the network. In order to fix this, the following lines can be added to the start of the loop in 'main.cpp'.

```
    // Check if WiFi is connected
    if (WiFi.status() != WL_CONNECTED) {
        Serial.println("WiFi disconnected. Reconnecting...");
        WiFi.begin(ssid, password); // Attempt to reconnect
        while (WiFi.status() != WL_CONNECTED) {
            delay(1000);
            Serial.println("Attempting to reconnect to WiFi...");
        }
        Serial.println("Reconnected to WiFi.");
    }
```

I've tested this out and it works as expected. Would you mind adding these lines in?

**Comment by nikisalli** [comment]
can you make a PR? so that I can merge it easily

**Comment by ElectronicallyE** [comment]
Yep, I’ll get onto that tomorrow. It’s late here down under.
