### ISSUE TITLE
如何更换地图

### ISSUE THREAD

**Issue by Du-Sivia** [nikisalli/esp32-minecraft-server#7]

**Comment by AlexC-0806** [comment]
It seems that the title of the issue translated is "How to change the map". Well, I made some small modifications in the code to make the map larger, but the effects are kinda bizarre. Here's what i changed:

- in "minecraft.cpp":
bool minecraft::player::join()
{
    uint8_t res = readHandShake();
    if (res == 1)
    {
        readRequest();
        delay(1000);
        writeResponse();
        uint64_t payload = readPing();
        writePong(payload);
        return false;
    }
    else if (res == 2)
    {
        if (!readLoginStart())
            return false;
        writeLoginSuccess();
    }
    connected = true;
    writeJoinGame();
    writePlayerPositionAndLook(0, 5, 0, 0, 0, 0x00);
    writeServerDifficulty();
//New writeChunk commands
    for (int i = -20; i < 20; i++)
    {
        for (int j = -20; j < 20; j++)
        {
            writeChunk(i, j);
        }
    }
// Removed the old writeChunk commands
    //    writeChunk(0, 0);
    //   writeChunk(0, 1);
    //   writeChunk(1, 0);
    //   writeChunk(1, 1);
    mc->broadcastPlayerInfo();
    mc->broadcastChatMessage(username + " joined the server", "Server");
    mc->broadcastSpawnPlayer();
    return true;
}

This way the map is larger but the map appears really strange when entering the game:
![image](https://github.com/user-attachments/assets/bea2c36f-b736-4b97-86c4-148cf03c8118)

**Comment by AlexC-0806** [comment]
I also added some commands to turn on and off the onboard LED and they work just fine, at least

**Comment by AlexC-0806** [comment]
Also, I noticed that lava for some reason has a grey texture, and many interactions with block don't work, but maybe @nikisalli did it to save memory on the ESP32, for example beds and spawn eggs don't work. Maybe on an ESP32-S3 with more memory (such as a N16R8 variant) could handle this heavier load.

**Comment by nikisalli** [comment]
on esp32 both compute and memory are limited, so I shrinked the block palette by some bits and informed the client of this. That's probably why blocks outside the bit range appear grey.

you may implement every world you want as long as you can keep in memory all the changes you do to the world or in case you don't wanna interact you may generate the world procedurally as you already attempted

**Comment by AlexC-0806** [comment]
> on esp32 both compute and memory are limited, so I shrinked the block palette by some bits and informed the client of this. That's probably why blocks outside the bit range appear grey.
> 
> you may implement every world you want as long as you can keep in memory all the changes you do to the world or in case you don't wanna interact you may generate the world procedurally as you already attempted

Thanks for the quick reply, what seems strange to me is that all the other chunks have random blocks in them. Do you have any idea on why this happens?

**Comment by AlexC-0806** [comment]
Also, how can I make that all chunks are rendered at the same time?
